# Generated by Django 4.1.6 on 2023-02-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_total', models.FloatField()),
                ('itens_pedido', models.ManyToManyField(to='core.itempedido')),
            ],
        ),
    ]
