# Generated by Django 4.1.6 on 2023-02-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nome',
            field=models.CharField(default='cliente', max_length=100),
        ),
    ]
