# Generated by Django 4.1.6 on 2023-02-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(to='core.itempedido'),
        ),
    ]
