# Generated by Django 4.1.6 on 2023-02-24 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tipoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.tipoproduto'),
            preserve_default=False,
        ),
    ]
