# Generated by Django 4.1.6 on 2023-02-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_produto_tipo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproduto',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
